<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Symfony\Component\Console\Input\InputArgument;

class AskCoinCommand extends Command
{
    protected function configure()
    {
        $this->setName('ask:scoin')
            ->setDescription('The command asks for the first and second currency')
            ->setHelp('This command allows you to enter the currency pair');
//                ->addArgument('firstcoin',  InputArgument::REQUIRED, 'Enter the first currency: ')
//                ->addArgument('secondcoin', InputArgument::REQUIRED, 'Enter the second currency: ');

        parent::configure(); // TODO: Change the autogenerated stub

    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $helper = $this->getHelper('question');

        $curr1 = $helper->ask($input, $output, new Question(
            "Enter your currency : ", "BTC"
        ));
        $curr2 = $helper->ask($input, $output, new Question(
            "Enter your second currency : ", "USD"
        ));



        $link = new LinkCreator($curr1, $curr2);

        $httpClient = new HttpClient();

        $response = $httpClient->getResponse($link);

        $ret = new ResponseParser($response)



        $message = sprintf("Your currencies are %s/%s", $curr1, $curr2);

        $output->writeln($message);

        return Command::SUCCESS;
//            parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}